version: "3.3"
services:
  registry:
    image: registry:latest
    container_name: registry
  loadbalance_registry:
    image: nginx:registry
    container_name: nginx_registry
    links:
      - registry
    ports:
      - "7000:8080"
